version: '3.9'

services:
  cloudflaretunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflaretunnel
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    command: tunnel --no-autoupdate run
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
    external: true
  backend:
    external: true
